apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ajiqbrainx/frontend:1
          ports:
            - containerPort: 8080

#Node Port service for the Azure Deployment 
 apiVersion: apps/v1
 kind: Service
 metadata:
   name: frontend-service
 spec:
   type: ClusterIP
   ports:
    -port: 8080
     targetPort: 8080
   selector:
     app: frontend
           
            
            
